import Head from 'next/head'
import Button from '../components/button'
import { t } from 'ttag.macro'
import dynamic from 'next/dynamic'
const RedButton = dynamic(
  () => import('../components/redButton'),
  { ssr: false }
)


export default function Home() {
  return (
    <div className={'container'}>
      <Head>
        <title>SWC - TTAG macro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{display: 'flex', flexDirection: 'column'}}>
        <br />
        <h1>{t`صفحه یافت نشد - خطای ۴۰۴`}</h1>
        <Button onClick={() => alert(`The locale is: ${process.env.NEXT_PUBLIC_LOCALE}`)}>{t`اینجا کلیک کنید`}</Button>
        <RedButton onClick={() => {}}>RedButton</RedButton>
      </main>
    </div>
  )
}
